server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leafdb
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

logging:
  level:
    org:
      springframework: INFO

aws-properties:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: ${AWS_BUCKET_NAME}
  region: ${AWS_REGION}

encryption-key: ${ENCRYPTION_KEY}